name = input('What is your name? ')
subject = input('What is your favorite subject? ')
print('%s\'s favorite subject in school is %s' % (name, subject))
print('What is name? %s' % (name))
print('What is subject? %s' % (subject))
print('%s\'s favorite subject in school is %s' % (name, subject))